/**
 * Returns the public URL of a pre-generated demo sign poster.
 * These are generated by the `generate-demo-signs` edge function
 * and stored in the `generated-assets` bucket.
 */
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;

export const getDemoSignUrl = (typeSlug = "se-vende", propSlug = "piso") =>
  `${SUPABASE_URL}/storage/v1/object/public/generated-assets/demo-signs/${typeSlug}/${propSlug}/poster.png`;
