// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvafmozggptfxwtwdogv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2YWZtb3pnZ3B0Znh3dHdkb2d2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA2NjU3OTUsImV4cCI6MjA4NjI0MTc5NX0._rk7wgDfvQDNRo0RK0NrP5cz4eSwMJZuvw-lhGUKR1Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});